name: ubuntu

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  ubuntu-latest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: cmake
        run: cmake -S . -B build -D CMAKE_BUILD_TYPE=Debug -DNADJIEB_MJPEG_STREAMER_BuildTests=On -DNADJIEB_MJPEG_STREAMER_MultipleHeaders=ON
      - name: build
        run: cmake --build build --config Debug --parallel 10
      - name: test
        run: cd build ; ctest -j 10 --output-on-failure
